/*
-- Query: select * from modelo
-- Date: 2017-06-17 23:37
*/
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (1,1,1,'CARGO 1519 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (2,5,1,'CityClass Executivo/Turismo 1p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (3,9,1,'25-320 E Constellation 6x2 Titan Tractor');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (4,10,1,'FH-12 380 GLOBETROTTER 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (5,10,1,'NL-12 360 EDC 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (6,7,1,'LS-1524 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (7,1,1,'F-350 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (8,7,1,'Accelo 815 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (9,8,1,'T-124 GA 360 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (10,7,1,'Atego 2429 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (11,8,1,'P-250 B 8x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (12,8,1,'R-470 A 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (13,8,1,'R-500 LA 6x4 HZ HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (14,7,1,'LS-1313 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (15,5,1,'DAILY CHASSI 70C16 HD MASSIMO 2p (diesel');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (16,1,1,'CARGO 1517 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (17,9,1,'16-210 H 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (18,2,1,'D-40 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (19,7,1,'Axor 2533 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (20,1,1,'CARGO 1419 Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (21,8,1,'P-114 GA 360 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (22,8,1,'R-440 A 4x2 3-Eixos/A 6x2 2p(dies.) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (23,8,1,'R-114 LA 380 4x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (24,8,1,'T-114 GB 330 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (25,5,1,'VERTIS 130V18 4x2  2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (26,7,1,'Atego 1726 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (27,8,1,'T-113 H 360 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (28,7,1,'Atego 3030 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (29,7,1,'L-1614 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (30,9,1,'7-110 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (31,9,1,'15-170/ 15-170 E WORKER 3-Eixos 2p (dies');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (32,5,1,'DAILY CHASSI 35.10/ 35.13/ 40.13 2p');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (33,8,1,'R-580 A 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (34,8,1,'P-94 GA 270 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (35,9,1,'17-210 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (36,10,1,'VM 260 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (37,1,1,'CARGO 3129 6x4 Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (38,8,1,'T-113 H 310 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (39,7,1,'1215 C 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (40,7,1,'LK-1618 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (41,9,1,'23-250 E 6x2 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (42,5,1,'DAILY VETRATO 45S17 4p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (43,7,1,'Axor 3340/ 3340 K 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (44,7,1,'L-1117 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (45,8,1,'P-250 B 8x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (46,10,1,'FMX 500 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (47,10,1,'FH 480 GLOBETROTTER 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (48,5,1,'DAILY CHASSI 40S14 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (49,1,1,'CARGO 1721 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (50,7,1,'L-1314 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (51,10,1,'FH-12 420 GLOBETROTTER 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (52,5,1,'DAILY CHASSI 55C17 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (53,7,1,'L-2325 6X4 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (54,7,1,'L-1620 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (55,1,1,'CARGO 1217 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (56,9,1,'24-280 E Constel. 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (57,10,1,'FM 480 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (58,8,1,'R-440 A 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (59,9,1,'16-220 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (60,7,1,'L-2219 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (61,7,1,'Axor 1933 S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (62,9,1,'8-140 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (63,10,1,'VM 310 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (64,1,1,'F-350 Tropicampo CD 2.8 (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (65,10,1,'FH-16 750 GLOBETROTTER 8X4 2p (die)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (66,1,1,'CARGO 1630 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (67,5,1,'DAILY GRAN FURGONE 45S17 4p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (68,7,1,'Atego 1518 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (69,9,1,'31-320 E Constellation 6x4 3-Eixos 2p (d');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (70,5,1,'DAILY GRAN FURGONE 55C16 4p ( diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (71,1,1,'CARGO 2324 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (72,10,1,'FH-540 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (73,8,1,'G-470 A 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (74,5,1,'DAILY MAX VAN 49.12/ 50.13 TB Int. 2p');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (75,1,1,'F-4000 TURBO(MWM) 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (76,9,1,'15-190 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (77,7,1,'L-1118 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (78,8,1,'P-124 CB 360 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (79,7,1,'2418 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (80,1,1,'CARGO 2622/ 2622 E 6x4 T 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (81,7,1,'L-1218 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (82,8,1,'R-420 LA 6x2 NA HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (83,5,1,'STRALIS NR 490-S46T 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (84,7,1,'1938-S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (85,10,1,'FM 370 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (86,7,1,'Atego 2428 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (87,8,1,'R-113 H 360 4x2 Top-Line 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (88,1,1,'CARGO 1415 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (89,7,1,'L-1118 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (90,5,1,'TECTOR STRADALE 240E25S 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (91,5,1,'DAILY GRAN FURGONE 45S14 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (92,10,1,'NL-12 410 EDC GOLD 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (93,7,1,'1728 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (94,9,1,'7-100 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (95,5,1,'DAILY CHASSI 35S14 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (96,5,1,'TECTOR 240E28 Attack 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (97,1,1,'CARGO 1719 Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (98,1,1,'F-4000 TURBO (CUMMINS) 4x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (99,9,1,'13-180 E Constellation 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (100,8,1,'G-440 A 4x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (101,7,1,'Atego 1418 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (102,5,1,'TECTOR 170E21 Attack 4x2 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (103,8,1,'P-114 CB 330 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (104,1,1,'CARGO 1215 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (105,9,1,'14-200 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (106,10,1,'FM 480 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (107,7,1,'Axor 3344 S 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (108,8,1,'R-114 GA 380 6x2 NZ/ 4x2 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (109,8,1,'T-124 LA 360 6X2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (110,5,1,'EUROCARGO 120-E15 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (111,9,1,'13-190 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (112,9,1,'18-310 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (113,8,1,'R-124 GB 360 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (114,9,1,'11-140 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (115,8,1,'R-114 GA 380 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (116,5,1,'DAILY CHASSI 35S14 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (117,7,1,'1721/ 1721 S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (118,8,1,'T-124 LA 420 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (119,1,1,'CARGO 1624 Turbo 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (120,9,1,'23-230 Constellat. 3-Eixos (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (121,7,1,'L-1418 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (122,9,1,'17-230 E Constellation 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (123,7,1,'L-2217 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (124,5,1,'DAILY MAXI FURGONE 55C17 4p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (125,8,1,'R-480 A 6x4 HIGHLINE 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (126,10,1,'FH-460 4x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (127,7,1,'ACTROS 4844 K 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (128,7,1,'L-1517 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (129,7,1,'L-1214 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (130,10,1,'FH-420 GLOBETROTTER 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (131,1,1,'CARGO 1114 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (132,1,1,'CARGO 1622 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (133,8,1,'T-124 GA 420 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (134,9,1,'11-130 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (135,7,1,'ACTROS 2651 LS 6X4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (136,9,1,'26-390 E Constel. 6x4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (137,1,1,'CARGO 2628 E 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (138,10,1,'FH-12 460 6x2 2p TA/TB (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (139,10,1,'VM 270 8X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (140,5,1,'STRALIS 460-S36T TA 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (141,5,1,'EUROCARGO 170-E21 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (142,1,1,'CARGO 1717/ 1717 E Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (143,7,1,'L-2013 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (144,10,1,'FM 400 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (145,5,1,'DAILY GRAN FURGONE 55C17 4p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (146,10,1,'NL-10 320 EDC 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (147,8,1,'R-124 GA 420 6x2 NZ/ 4x2 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (148,9,1,'12-140 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (149,8,1,'R-420 A 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (150,9,1,'13-160 E DELIVERY 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (151,10,1,'NL-12 410 EDC GOLD 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (152,9,1,'13-190 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (153,7,1,'1720-A 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (154,10,1,'N-10 280 XH 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (155,10,1,'NL-12 410 EDC 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (156,1,1,'CARGO 1619 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (157,8,1,'G-360 A 4x2 3-Eixos/A 6x2 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (158,10,1,'FM 370 4X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (159,1,1,'CARGO 1314 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (160,5,1,'STRALIS HI-WAY 800-S48TZ 6X4 (diel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (161,8,1,'R-143 H 450 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (162,7,1,'Axor 4140 K 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (163,5,1,'DAILY FURGAO 49.12/ 50.13 4p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (164,7,1,'L-1621 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (165,8,1,'G-420 A 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (166,8,1,'R-114 GA 360 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (167,9,1,'26-260/ 26-260 WORKER 6x4 3-Eixos 2p (di');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (168,5,1,'STRALIS 490-S40T TB Eurot.(dies)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (169,7,1,'1414 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (170,2,1,'19000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (171,5,1,'STRALIS 500-S33T TB 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (172,9,1,'17-190 E Constellation 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (173,9,1,'16-170 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (174,7,1,'Atego 2730 6X4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (175,8,1,'T-124 LA 400 6x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (176,10,1,'FH-500 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (177,5,1,'DAILY CHASSI 45S14 Cab.Dup. 4p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (178,1,1,'CARGO 2218 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (179,5,1,'VERTIS 90V16 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (180,8,1,'G-470 A 4x2 3-Eixos/ A 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (181,8,1,'R-480 A 8x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (182,2,1,'12000 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (183,9,1,'13-130 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (184,7,1,'Axor 3344/ 3344 K 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (185,7,1,'LS-1634 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (186,7,1,'LK-2635 6x4 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (187,1,1,'CARGO 2217 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (188,2,1,'14000 Turbo 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (189,5,1,'DAILY FURGÃO CITY 38.13 4p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (190,5,1,'DAILY Minibus Fretam. 45S17 (dies.) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (191,9,1,'26-260 E Constellation 6x4 3-Eixos 2p (d');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (192,7,1,'1318 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (193,10,1,'NL-12 410 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (194,7,1,'2038 S 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (195,5,1,'STRALIS NR 740-S41T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (196,10,1,'NL-10 340 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (197,8,1,'R-124 GB 420 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (198,7,1,'L-1317 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (199,1,1,'CARGO 2428 E T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (200,9,1,'24-320 E Constellation 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (201,7,1,'1723-S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (202,8,1,'P-114 GA 330 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (203,5,1,'EUROCARGO 260-E25 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (204,5,1,'CURSOR 450E 33 T 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (205,5,1,'STRALIS 450-S33T TA 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (206,5,1,'CityClass Executivo/Turismo (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (207,8,1,'R-114 GB 320 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (208,7,1,'1718 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (209,1,1,'CARGO 1419 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (210,10,1,'FMX 400 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (211,8,1,'R-420 A 4x2 HIGHLINE 3-Eixos/ A 6x2 2p (');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (212,5,1,'DAILY CHASSI 35S14 CD 4p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (213,9,1,'8-150/ 8-150 E WORKER 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (214,1,1,'F-19000 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (215,7,1,'ACTROS 2546 LS 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (216,8,1,'R-580 A 4x2 3-Eixos/ A 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (217,10,1,'NL-12 410 EDC 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (218,8,1,'R-440 A 6x4 HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (219,10,1,'FH-12 380 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (220,9,1,'5-150 E DELIVERY 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (221,7,1,'LS-1634 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (222,9,1,'17-190 E Worker 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (223,7,1,'Axor 2641 S 6x4 2P (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (224,5,1,'POWERSTAR 450 E37 (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (225,1,1,'F-4000 Tropicampo CD 3.9 TDI (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (226,7,1,'Axor 4144 K 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (227,8,1,'P-310 B 4x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (228,9,1,'15-180/ 15-180 E WORKER 3-Eixos 2p (dies');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (229,5,1,'STRALIS HD 450-S38T 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (230,7,1,'Axor 2533 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (231,8,1,'T-113 H 360 4x2 Top-Line 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (232,7,1,'Axor 2640 S 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (233,8,1,'G-420 A 4x2 3-Eixos/ A 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (234,7,1,'Axor 3344 S 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (235,8,1,'P-93 H 250 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (236,9,1,'14-210 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (237,10,1,'FH-460 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (238,7,1,'2428 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (239,2,1,'11000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (240,7,1,'712 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (241,7,1,'608 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (242,10,1,'FMX 370 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (243,7,1,'Atego 1315 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (244,10,1,'VM 330 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (245,10,1,'FH 520 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (246,9,1,'19-330 E Constellation 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (247,9,1,'16-220 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (248,7,1,'L-1316 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (249,7,1,'L-1620 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (250,7,1,'LS-1941 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (251,10,1,'NH-12 380 GLOBETROTTER 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (252,5,1,'TRAKKER 410-T48 Eurot. 6x4 (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (253,10,1,'FH 480 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (254,8,1,'P-360 A 4x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (255,8,1,'P-94 GA 310 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (256,10,1,'VM-17 240 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (257,8,1,'G-440 A 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (258,7,1,'Axor 3131 6x4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (259,5,1,'TRAKKER 740-T48 Eurot.6X4 (dies.) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (260,10,1,'FMX 460 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (261,9,1,'19-360 Constellat. Tractor (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (262,7,1,'LS-1924 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (263,9,1,'26-280 E Constel. 6x4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (264,8,1,'R-124 LA 420 6x4 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (265,9,1,'23-210 6x2 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (266,8,1,'R-124 LA 360 6x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (267,5,1,'STRALIS 600-S40T TB 6x2 Eurot.(dies)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (268,7,1,'ACTROS 2646 LS 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (269,1,1,'CARGO 816 E Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (270,8,1,'R-124 GA 420 4x2 NZ 2p (diesel) / Millen');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (271,7,1,'2638 S 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (272,7,1,'Axor 4141 K 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (273,10,1,'VM 270 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (274,1,1,'CARGO 1621 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (275,7,1,'L-1318 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (276,1,1,'F-14000 HD 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (277,8,1,'R-560 A 6x2 HIGHLINE (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (278,7,1,'Atego 1725 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (279,8,1,'T-113 H 360 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (280,10,1,'NL-10 310 6X4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (281,10,1,'FH-12 420 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (282,1,1,'CARGO 2630 6X4 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (283,2,1,'19000 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (284,1,1,'F-MAXX F-12000 5.9 162cv TD (diesel) 6p');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (285,8,1,'T-113 H 360 4x2 Top-Line 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (286,10,1,'FH 520 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (287,5,1,'STRALIS 800-S44T TA 6x4 Eurot.(dies)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (288,5,1,'EUROCARGO 170-E21 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (289,8,1,'P-340 A 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (290,7,1,'Axor 2040 S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (291,8,1,'G-440 B 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (292,10,1,'VM 330 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (293,7,1,'L-1519 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (294,8,1,'R-124 LA 420 4x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (295,10,1,'N-10 300 XH 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (296,5,1,'STRALIS 530-S36T TB 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (297,7,1,'1944-S 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (298,7,1,'L-1630 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (299,5,1,'TECTOR 170E25 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (300,2,1,'D-60 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (301,5,1,'STRALIS 600-S44T TA 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (302,9,1,'23-230 WORKER 3-Eixos 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (303,7,1,'LS-1632 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (304,9,1,'15-170/ 15-170 E WORKER 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (305,7,1,'L-1414 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (306,7,1,'Atego 2730B 6X4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (307,10,1,'VM 330  4X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (308,5,1,'TECTOR 260E30 6X4 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (309,7,1,'LS-1941 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (310,1,1,'CARGO 1317/ 1317 E T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (311,8,1,'T-124 GA 420 6x2 NZ 2p (diesel) / Millen');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (312,8,1,'R-440 A 8x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (313,8,1,'G-420 B 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (314,2,1,'11000 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (315,1,1,'CARGO 1319 E Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (316,8,1,'P-94 CB 270 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (317,10,1,'FH-12 460 6x4 2p TA/TB (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (318,1,1,'F-16000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (319,1,1,'CARGO 2423 E 6x2 Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (320,1,1,'CARGO 2319 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (321,9,1,'35-300 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (322,7,1,'Atego 2425 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (323,7,1,'L-1518 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (324,10,1,'NL-10 310 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (325,1,1,'CARGO 2831 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (326,3,1,'190 H 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (327,5,1,'STRALIS 490-S44T TB 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (328,7,1,'Axor 2644 S/LS 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (329,10,1,'FH 520 GLOBETROTTER 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (330,8,1,'T-113 H 320 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (331,7,1,'Axor 2035 S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (332,1,1,'F-4000 4x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (333,9,1,'12-140 Turbo 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (334,1,1,'CARGO 6332 E 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (335,9,1,'17-250 E Constellation Tractor 4x2 2p (d');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (336,5,1,'DAILY CHASSI 35S14 Cab.Dup. 4p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (337,1,1,'CARGO 1517 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (338,7,1,'Atego 1718 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (339,7,1,'708 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (340,9,1,'8-160 E DELIVERY 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (341,7,1,'Atego 1725 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (342,7,1,'L-1114 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (343,7,1,'ATRON 2729 B 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (344,5,1,'STRALIS 600-S40T TB 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (345,8,1,'P-124 CB 420 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (346,1,1,'CARGO 1622 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (347,7,1,'Axor 3341 S 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (348,5,1,'TECTOR 170E22 Attack 4x2 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (349,7,1,'Axor 3341 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (350,9,1,'31-260 E Constellation 6x4 3-Eixos 2p (d');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (351,1,1,'CARGO 1218 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (352,8,1,'T-124 LA 420 4x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (353,7,1,'Atego 1719 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (354,10,1,'FH-460 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (355,2,1,'D-70 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (356,1,1,'CARGO 5032 E 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (357,8,1,'R-113 H 360 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (358,10,1,'NL-12 400 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (359,7,1,'912 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (360,1,1,'CARGO 1731 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (361,8,1,'P-250 B 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (362,7,1,'L-1514 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (363,7,1,'1420 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (364,5,1,'TECTOR 240E22 Attack 6x2 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (365,1,1,'CARGO 1119 Turbo 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (366,10,1,'NH-12 460 6x2 2p TA/TB (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (367,10,1,'FH-540 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (368,8,1,'P-360 A 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (369,10,1,'FM 440 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (370,7,1,'1718-K 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (371,7,1,'L-1517 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (372,10,1,'FH 440 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (373,7,1,'Axor 2044 S 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (374,8,1,'R-124 GA 360 6x2 NZ/ 4x2 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (375,7,1,'1720 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (376,5,1,'DAILY CHASSI 55C17 CD 4p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (377,5,1,'STRALIS 450-S33T TB 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (378,2,1,'6000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (379,9,1,'15-190 E Worker 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (380,10,1,'VM 310 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (381,8,1,'R-500 A 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (382,9,1,'17-310 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (383,7,1,'L-1618 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (384,5,1,'EUROCARGO/ATTACK 170-E22 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (385,8,1,'T-124 LA 360 4x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (386,7,1,'1214 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (387,8,1,'R-470 LA 6x2 NA HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (388,10,1,'FMX 440 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (389,5,1,'CityClass  Urb./Escolar/SPTrans 1p');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (390,7,1,'Atego 1315 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (391,9,1,'15-180 E Constellation 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (392,1,1,'F-350 Tropicampo CD 3.9  TDI (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (393,7,1,'L-2635 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (394,7,1,'LK-1620 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (395,5,1,'TECTOR 240E25 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (396,1,1,'F-21000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (397,8,1,'R-124 GB 360 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (398,8,1,'P-420 B 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (399,8,1,'G-400 A 4x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (400,8,1,'R-124 GA 400 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (401,10,1,'FH-540 GLOBETROTTER 4X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (402,7,1,'Axor 2826 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (403,10,1,'NL-12 360 EDC GOLD 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (404,2,1,'22000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (405,1,1,'F-MAXX 816e 162cv (diesel) 6p(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (406,10,1,'FH-500 GLOBETROTTER 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (407,8,1,'P-114 CA 360 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (408,7,1,'ATRON 1635 S 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (409,9,1,'17-280 E Constellation 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (410,10,1,'NL-10 320 EDC GOLD 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (411,10,1,'VM-23 240 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (412,8,1,'P-310 A 4x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (413,8,1,'R-420 A 4x2 HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (414,7,1,'LS-1519 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (415,10,1,'VM 270 8X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (416,9,1,'16-170 BT 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (417,10,1,'FMX 480 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (418,1,1,'CARGO 2626 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (419,10,1,'NH-12 420 GLOBETROTTER 6X4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (420,5,1,'STRALIS 600-S44T TB 6x2 Eurot.(dies)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (421,1,1,'CARGO 2421 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (422,5,1,'DAILY CHASSI 55C16 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (423,7,1,'Axor 2644 S 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (424,10,1,'NL-10 320 EDC 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (425,8,1,'P-114 GB 330 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (426,5,1,'DAILY FURG/ CITY FURG.35.10/40.13 4p');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (427,8,1,'T-124 GA 360 4x2 NZ 2p (diesel) / Millen');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (428,5,1,'TRAKKER 720-T42T 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (429,10,1,'FH-460 GLOBETROTTER 8X2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (430,10,1,'FM-12 380 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (431,9,1,'22-160 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (432,8,1,'R-400 A 6x2 HIGHLINE 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (433,9,1,'23-310 6x2 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (434,8,1,'G-360 A 4x2 (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (435,5,1,'DAILY MinibusTurismo 50C17 (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (436,5,1,'STRALIS NR 570-S46T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (437,10,1,'FH-460 GLOBETROTTER 6X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (438,9,1,'25-370 E Constellation 6x2 Tractor 2p (d');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (439,1,1,'CARGO 1832 E Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (440,8,1,'P-114 CB 360 6x4 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (441,10,1,'FH 400 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (442,7,1,'LS-1630 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (443,8,1,'G-440 B 8x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (444,10,1,'NL-12 360 EDC GOLD 6X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (445,8,1,'R-114 LA 380 6x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (446,7,1,'L-1313 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (447,8,1,'R-124 GA 470 6x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (448,8,1,'P-94 DB 260 6x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (449,9,1,'13-190 E Constellation 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (450,7,1,'ACTROS 2646 S 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (451,5,1,'EUROTECH TZ 740-E42 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (452,9,1,'17-300 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (453,8,1,'P-250 B 6x4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (454,7,1,'L-1214 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (455,5,1,'STRALIS 800-S48T TA 6x4 Eurot.(dies)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (456,5,1,'EUROTRAKKER 380-E38 H 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (457,8,1,'R-500 A 6x4 HIGHLINE 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (458,8,1,'R-124 LA 420 6x2 NA 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (459,10,1,'NH-12 380 GLOBETROTTER 6X4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (460,8,1,'P-250 B 4x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (461,10,1,'FH-500 GLOBETROTTER 4X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (462,10,1,'NL-12 360 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (463,7,1,'L-1630 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (464,1,1,'CARGO 1418 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (465,10,1,'VM 220 6x2 2p (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (466,2,1,'13000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (467,5,1,'EUROCARGO 150-E18 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (468,1,1,'CARGO 2425 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (469,1,1,'CARGO 1731 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (470,9,1,'8-150 E DELIVERY 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (471,9,1,'6-80 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (472,8,1,'G-380 A 4x2 3-Eixos/ A 6x2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (473,8,1,'R-470 LA 4x2 HZ HIGHLINE 3-Eixos 2p (die');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (474,7,1,'ATRON 1319 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (475,7,1,'1214 C 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (476,9,1,'13-150 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (477,10,1,'NL-10 340 6X4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (478,7,1,'Axor 2541 S 6x2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (479,7,1,'Accelo 715C 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (480,8,1,'R-114 GA 320 4x2 NZ 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (481,1,1,'CARGO 3222 Turbo 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (482,9,1,'25-420 Constellation 6x2 2p (Diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (483,1,1,'F-13000 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (484,8,1,'P-420 A 6x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (485,5,1,'DAILY FURGONE 35S14 4p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (486,10,1,'FH-420 4X2 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (487,5,1,'TECTOR 170E28 4x2 2p (dies.)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (488,10,1,'FMX 420 8X4 2p (diesel) (E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (489,10,1,'N-10 280 H 4X2 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (490,7,1,'L-1614 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (491,1,1,'CARGO 1314 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (492,1,1,'F-13000 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (493,8,1,'T-124 GA 360 6x2 NZ 2p (diesel) / Millen');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (494,7,1,'Atego 1418 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (495,1,1,'CARGO 5031 6x4 T 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (496,10,1,'FMX 480 8x4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (497,1,1,'CARGO 1313 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (498,10,1,'NH-12 380 6X4 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (499,5,1,'CityClass Fretamento (diesel)(E5)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (500,7,1,'1721/ 1721 S 3-Eixos 2p (diesel)');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (501,12,2,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (502,12,6,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (503,13,6,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (504,13,7,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (505,14,7,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (506,13,6,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (507,14,2,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (508,14,6,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (509,13,5,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (510,13,4,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (511,12,6,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (512,11,5,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (513,11,6,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (514,14,4,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (515,11,3,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (516,11,5,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (517,12,3,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (518,13,4,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (519,14,7,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (520,14,3,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (521,14,3,'Sider');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (522,13,2,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (523,11,6,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (524,12,6,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (525,12,2,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (526,14,7,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (527,11,5,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (528,11,4,'Sider');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (529,14,7,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (530,13,3,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (531,11,4,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (532,13,4,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (533,11,4,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (534,12,2,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (535,14,6,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (536,11,3,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (537,12,5,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (538,11,6,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (539,12,6,'Sider');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (540,11,4,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (541,11,4,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (542,13,5,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (543,12,3,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (544,12,3,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (545,11,4,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (546,14,7,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (547,12,5,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (548,11,2,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (549,13,6,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (550,13,6,'Carga Seca');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (551,13,3,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (552,12,3,'Sider');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (553,13,5,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (554,13,3,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (555,11,4,'Frigorifico');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (556,13,3,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (557,13,7,'Basculante');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (558,12,4,'Sider');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (559,14,5,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (560,14,3,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (561,13,2,'Florestal');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (562,11,2,'Graneleiro');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (563,11,2,'Caçamba');
INSERT INTO `modelo` (`idModelo`,`idMarca`,`idTipoVeiculo`,`Descricao`) VALUES (564,13,3,'Graneleiro');
